---
title: "Lab-grades"
author: "Paula de Miguel Sánchez"
format: html
---

```{r}
here::i_am("lab-grades.Rproj")

library(here)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(knitr)
```

### Question 1

```{r}
courses <- read_csv(here("courses.csv"))
```

### Question 2

```{r}
courses |>
  arrange(course) |>
  rename(
    `course name`     = course,
    identifier        = course_id,
    `number of grades` = nb_grades
  ) |>
  knitr::kable()
```
### Question 3
```{r}
students <- read_csv(here("students.csv"))
students <- students |>
  mutate(
    birth_date = as.Date(birth_date),
    sex= factor(sex),
    group = factor(group),
    id = as.integer(id)
  )
class(students$birth_date)
class(students$sex)
class(students$group)
class(students$id)
```
The `birth_date` column of the `students`data frame is of class Date

The `sex`column is correctly identified as a factor

### Question 4
```{r}
grades <- read_delim(
  here("grades.csv"),
  delim = "|",
  na = "unknown"
)
```
### Question 5
```{r}
students |>
  count(group) |>
  ggplot(aes(x=group, y = n)) +
  geom_col(fill = "lavenderblush2") +
  theme_minimal() +
  labs(
    title = "Number of students per group", 
    x = "Group",
    y = "Count"
  )
```
The bar plot shows the number of students that are in each group

### Question 6
```{r}
students |>
  ggplot(aes(x = group, fill = sex)) +
  geom_bar(position = "fill") +
  theme_minimal() +
  labs(
    title = "Gender balance by group",
    x = "Group",
    y = "Proportion"
  )
```
### Question 7
```{r}
students <- students |>
  mutate(
    age = time_length(today() - birth_date, unit = "year") |> round() 
    )
students |>
  ggplot(aes(x=age)) +
  geom_histogram(binwidth=1, fill = "orchid4", color = "white") +
  theme_minimal() +
  labs(
    title = "Distribution of students ages", 
    x = "Age",
    y= "Count"
  )
  
```

The histogram below displays the age distribution of the students

### Question 8
```{r}
students |>
  group_by(group) |>
  summarise(
    median_age = round(median(age, na.rm = TRUE))
  ) |>
   knitr::kable()
```

### Question 9
```{r}

```

